<a href="https://colab.research.google.com/github/Hemkush/Python_Practice/blob/main/Exam3_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [ ]:
ser = Series([1,2,-4,8])
ser

0    1
1    2
2   -4
3    8
dtype: int64

In [ ]:
# Create from dictionary

# The zip() function returns a zip object,
# which is an iterator of tuples where the first item in each passed iterator is paired together,
# and then the second item in each passed iterator are paired together etc.
print(list(zip('abcd', [1,-2,3,-4])))
D = {key:val for key,val in zip('abcd', [1,-2,3,-4])}
print(D)
ser = Series(D)
ser

[('a', 1), ('b', -2), ('c', 3), ('d', -4)]
{'a': 1, 'b': -2, 'c': 3, 'd': -4}


a    1
b   -2
c    3
d   -4
dtype: int64

In [ ]:
# Drop values
ser.drop('c')

a    1
b   -2
d   -4
dtype: int64

In [ ]:
ser

a    1
b   -2
c    3
d   -4
dtype: int64

In [ ]:
# Deleting values
del ser['c']
ser

a    1
b   -2
d   -4
dtype: int64

In [ ]:
# Index object - similar to dictionary keys, returns an index array
ser.index

Index(['a', 'b', 'd'], dtype='object')

In [ ]:
# Values - similar to dictionary values, returns an array
ser.values

array([ 1, -2, -4])

In [ ]:
# Check for membership
print('e' in ser.index)
print(-2 in ser.values)

False
True


#DataFrame

In [ ]:
# Dictionary of equal-length sequences
df = DataFrame({'a': [1,2,3], 'b': (4,5,6), 'c': np.array([7,8,9])}, index=[1,2,3])
df

a  b  c
1  1  4  7
2  2  5  8
3  3  6  9

In [ ]:
# Dictionary of Series objects
print(-ser)
df = DataFrame({'Original': ser, 'Negated': -ser})
df

a   -1
b    2
d    4
dtype: int64


Original  Negated
a         1       -1
b        -2        2
d        -4        4

In [ ]:
# 2-d array
df = DataFrame(np.random.rand(3,3), columns=['a','b','c'],  index=[1,2,3])
df

a         b         c
1  0.536960  0.187910  0.704525
2  0.671409  0.972261  0.026503
3  0.717487  0.501332  0.999795

In [ ]:
# DataFrame values
print(df.values)
type(df.values)

[[0.53696049 0.18791019 0.70452516]
 [0.67140894 0.97226076 0.02650339]
 [0.71748699 0.50133243 0.99979458]]


numpy.ndarray

In [ ]:
# Basic column indexing: [] vs. [[]]
print(df)
print(df['b'])
print(df[['b','c']])
print(df.b)
print(type(df.b))

          a         b         c
1  0.536960  0.187910  0.704525
2  0.671409  0.972261  0.026503
3  0.717487  0.501332  0.999795
1    0.187910
2    0.972261
3    0.501332
Name: b, dtype: float64
          b         c
1  0.187910  0.704525
2  0.972261  0.026503
3  0.501332  0.999795
1    0.187910
2    0.972261
3    0.501332
Name: b, dtype: float64
<class 'pandas.core.series.Series'>


In [ ]:
# Columns and rows: loc - lable-based index
print(df)
print(df[['a','b']].loc[[1,2]])
print(df.loc[[1,2],['a','b']])

          a         b         c
1  0.536960  0.187910  0.704525
2  0.671409  0.972261  0.026503
3  0.717487  0.501332  0.999795
          a         b
1  0.536960  0.187910
2  0.671409  0.972261
          a         b
1  0.536960  0.187910
2  0.671409  0.972261


In [ ]:
# Updating values using .loc

df.loc[1,'a'] = np.random.rand()
df

a         b         c
1  0.241304  0.187910  0.704525
2  0.671409  0.972261  0.026503
3  0.717487  0.501332  0.999795

In [ ]:
# .iloc method: integer-based index
print(df)
df.iloc[:2, 2:]

          a         b         c
1  0.241304  0.187910  0.704525
2  0.671409  0.972261  0.026503
3  0.717487  0.501332  0.999795


c
1  0.704525
2  0.026503

In [ ]:
# Creating new columns - New value(s) will be broadcast (if applicable)
print(df)
df['d'] = np.random.rand(3)
df

          a         b         c
1  0.241304  0.187910  0.704525
2  0.671409  0.972261  0.026503
3  0.717487  0.501332  0.999795


a         b         c         d
1  0.241304  0.187910  0.704525  0.874587
2  0.671409  0.972261  0.026503  0.368017
3  0.717487  0.501332  0.999795  0.190770

In [ ]:
ser = Series(np.random.rand(3))
ser

0    0.769148
1    0.997807
2    0.213957
dtype: float64

In [ ]:
df['e'] = ser
df

a         b         c         d         e
1  0.241304  0.187910  0.704525  0.874587  0.997807
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN

In [ ]:
# Dropping rows
print(df)
df.drop(1, axis=0)

          a         b         c         d         e
1  0.241304  0.187910  0.704525  0.874587  0.997807
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN


a         b         c         d         e
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN

In [ ]:
# Dropping columns

df.drop('e', axis=1)

a         b         c         d
1  0.241304  0.187910  0.704525  0.874587
2  0.671409  0.972261  0.026503  0.368017
3  0.717487  0.501332  0.999795  0.190770

#Filtering with Series and DataFrames

In [ ]:
df

a         b         c         d         e
1  0.241304  0.187910  0.704525  0.874587  0.997807
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN

In [ ]:
# Column filter
df.loc[:, np.array([True,False,True,True,False])]

a         c         d
1  0.241304  0.704525  0.874587
2  0.671409  0.026503  0.368017
3  0.717487  0.999795  0.190770

In [ ]:
df

a         b         c         d         e
1  0.241304  0.187910  0.704525  0.874587  0.997807
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN

In [ ]:
# Identify values greater than 0.5
print(df)
mask = df > 0.5
mask

          a         b         c         d         e
1  0.241304  0.187910  0.704525  0.874587  0.997807
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN


a      b      c      d      e
1  False  False   True   True   True
2   True   True  False  False  False
3   True   True   True  False  False

In [ ]:
# Apply mask to DataFrame
df[mask]

a         b         c         d         e
1       NaN       NaN  0.704525  0.874587  0.997807
2  0.671409  0.972261       NaN       NaN       NaN
3  0.717487  0.501332  0.999795       NaN       NaN

In [ ]:
# Apply any or all method to mask - down each column (axis=0), across each row (axis=1)
print(mask)
amask = mask.any(axis=0)
amask

       a      b      c      d      e
1  False  False   True   True   True
2   True   True  False  False  False
3   True   True   True  False  False


a    True
b    True
c    True
d    True
e    True
dtype: bool

In [ ]:
# Apply amask to DataFrame - must match dimensions
print(df)
df.loc[:,amask]

          a         b         c         d         e
1  0.241304  0.187910  0.704525  0.874587  0.997807
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN


a         b         c         d         e
1  0.241304  0.187910  0.704525  0.874587  0.997807
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN

In [ ]:
# Apply filter inline
print(df)
df[df > 0.5]

          a         b         c         d         e
1  0.241304  0.187910  0.704525  0.874587  0.997807
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN


a         b         c         d         e
1       NaN       NaN  0.704525  0.874587  0.997807
2  0.671409  0.972261       NaN       NaN       NaN
3  0.717487  0.501332  0.999795       NaN       NaN

In [ ]:
# Apply filter based on column values
print(df)
df['color'] = 'blue', 'green', 'blue'
print(df)
#print(df['color'] == 'blue')
df[df['color'] == 'blue']

          a         b         c         d         e
1  0.241304  0.187910  0.704525  0.874587  0.997807
2  0.671409  0.972261  0.026503  0.368017  0.213957
3  0.717487  0.501332  0.999795  0.190770       NaN
          a         b         c         d         e  color
1  0.241304  0.187910  0.704525  0.874587  0.997807   blue
2  0.671409  0.972261  0.026503  0.368017  0.213957  green
3  0.717487  0.501332  0.999795  0.190770       NaN   blue


a         b         c         d         e color
1  0.241304  0.187910  0.704525  0.874587  0.997807  blue
3  0.717487  0.501332  0.999795  0.190770       NaN  blue

In [ ]:
# Apply filter to specific column
print(df)
print('\n===\n')
print(df['b'][df['color'] == 'green'])
print('\n===\n')
print(df.loc[df['color'] == 'blue', 'b'])

          a         b         c         d         e  color
1  0.241304  0.187910  0.704525  0.874587  0.997807   blue
2  0.671409  0.972261  0.026503  0.368017  0.213957  green
3  0.717487  0.501332  0.999795  0.190770       NaN   blue

===

2    0.972261
Name: b, dtype: float64

===

1    0.187910
3    0.501332
Name: b, dtype: float64


In [ ]:
# Combine filtering with assignment
print(df)
df.loc[df['color'] == 'green', 'b'] = 0
df

          a         b         c         d         e  color
1  0.241304  0.187910  0.704525  0.874587  0.997807   blue
2  0.671409  0.972261  0.026503  0.368017  0.213957  green
3  0.717487  0.501332  0.999795  0.190770       NaN   blue


a         b         c         d         e  color
1  0.241304  0.187910  0.704525  0.874587  0.997807   blue
2  0.671409  0.000000  0.026503  0.368017  0.213957  green
3  0.717487  0.501332  0.999795  0.190770       NaN   blue

#Descriptive Statistics

In [ ]:
# Create series object
ser = Series(np.random.randn(100))
ser

0     0.309546
1    -0.174861
2    -0.432033
3     0.216908
4     0.191220
        ...   
95   -0.700661
96   -1.346718
97    1.689988
98    1.369533
99   -0.637929
Length: 100, dtype: float64

In [ ]:
# .describe method
ser.describe()

count    100.000000
mean      -0.004439
std        1.137955
min       -3.746814
25%       -0.611879
50%       -0.017890
75%        0.743752
max        3.061404
dtype: float64

In [ ]:
# Create DataFrame object
df = DataFrame(np.random.randn(100,3))
df

0         1         2
0   0.450001 -0.469891 -0.504152
1   0.349408 -0.349109  1.110046
2   1.358073  1.526329  1.319001
3  -1.247946  0.937980 -0.623077
4   1.496566  0.218319  1.878840
..       ...       ...       ...
95 -1.338659  0.967846  1.087234
96  1.274515 -0.158375  0.356222
97  0.527265  0.168064  0.939376
98  0.448633  1.810441 -1.076158
99  0.154805  1.575933  1.525206

[100 rows x 3 columns]

In [ ]:
df.describe()

0           1           2
count  100.000000  100.000000  100.000000
mean    -0.057371    0.130013    0.155655
std      1.117534    0.900467    1.048553
min     -3.045372   -1.532088   -2.396138
25%     -0.692252   -0.534969   -0.625738
50%      0.099506    0.106523    0.123118
75%      0.549179    0.839220    0.940647
max      2.941109    2.509275    2.452919

In [ ]:
df.sum(axis=0)

0    -5.737057
1    13.001332
2    15.565453
dtype: float64

In [ ]:
# Correlation matrix: columns
df.corr()

0         1         2
0  1.000000 -0.005647  0.055264
1 -0.005647  1.000000  0.175900
2  0.055264  0.175900  1.000000

In [ ]:
# Create categorical series
cser = Series(['green'] * 20 + ['red'] * 25 + ['blue'] * 10)
cser.head(5)

0    green
1    green
2    green
3    green
4    green
dtype: object

In [ ]:
# Unique values
cser.unique()

array(['green', 'red', 'blue'], dtype=object)

In [ ]:
cser.value_counts()

red      25
green    20
blue     10
Name: count, dtype: int64

In [ ]:
# Membership
cser.isin(['green','red']).sum()

np.int64(45)

#Arithmetic Operations and Data Alignment

In [ ]:
# Create Series objects
ser1 = Series([1,2,3])
ser2 = Series([1,2,3], index=[1,2,3])
DataFrame({'col1': ser1, 'col2': ser2})

col1  col2
0   1.0   NaN
1   2.0   1.0
2   3.0   2.0
3   NaN   3.0

In [ ]:
# Arithmetic between Series and scalar
ser1 + 5

0    6
1    7
2    8
dtype: int64

In [ ]:
# Arithmetic between Series and sequence
ser1 + np.array([10,20,30]) # works for list and tuples too

0    11
1    22
2    33
dtype: int64

In [ ]:
# Arithmetic between two Series objects
ser1 + ser2

0    NaN
1    3.0
2    5.0
3    NaN
dtype: float64

In [ ]:
# Arithmetic methods - .add, .sub, .div, .floordiv, .mul, .pow
ser1.add(ser2, fill_value=5)

0    6.0
1    3.0
2    5.0
3    8.0
dtype: float64

In [ ]:
# Create two DataFrames
df1 = DataFrame(np.random.rand(3,3))
df1

0         1         2
0  0.885892  0.870339  0.805537
1  0.871773  0.593007  0.454832
2  0.585748  0.821108  0.382769

In [ ]:
df2 = DataFrame(np.random.rand(3,3), index=[1,2,3], columns=[1,2,3])
df2

1         2         3
1  0.336052  0.070709  0.503607
2  0.068289  0.890883  0.745312
3  0.857603  0.945540  0.366128

In [ ]:
# Perform operation between DataFrames
df1 + df2

0         1         2   3
0 NaN       NaN       NaN NaN
1 NaN  0.929059  0.525541 NaN
2 NaN  0.889397  1.273653 NaN
3 NaN       NaN       NaN NaN

In [ ]:
# Perform operation between DataFrame values
print(df1.values)
print(df2.values)
DataFrame(df1.values + df2.values)

[[0.88589223 0.87033851 0.80553718]
 [0.87177289 0.59300728 0.45483248]
 [0.58574798 0.82110766 0.38276929]]
[[0.33605205 0.07070889 0.50360697]
 [0.06828947 0.89088327 0.74531156]
 [0.85760263 0.94554019 0.36612829]]


0         1         2
0  1.221944  0.941047  1.309144
1  0.940062  1.483891  1.200144
2  1.443351  1.766648  0.748898

#Function Application and Mapping

Series or DataFrame objects:

- Series .map method - Applies function to each element in Series
- DataFrame .apply method - Applies function column- or row-wise
- DataFrame .applymap method - Applies function to each element in DataFrame

In [ ]:
# Apply NumPy universal function
df = DataFrame(np.random.rand(3,5))
print(df)
np.exp(df)

          0         1         2         3         4
0  0.207582  0.147820  0.555799  0.841771  0.930090
1  0.440490  0.394001  0.087994  0.085431  0.787785
2  0.558558  0.440427  0.897610  0.184026  0.413851


0         1         2         3         4
0  1.230698  1.159304  1.743334  2.320473  2.534737
1  1.553468  1.482902  1.091982  1.089186  2.198522
2  1.748149  1.553370  2.453731  1.202047  1.512631

In [ ]:
# Series map method - Numerical computation
ser = Series(np.random.rand(10))
print(ser)
ser.map(lambda x: x ** 2)

0    0.871425
1    0.133014
2    0.522957
3    0.905115
4    0.705681
5    0.953598
6    0.017655
7    0.094681
8    0.272722
9    0.366757
dtype: float64


0    0.759381
1    0.017693
2    0.273484
3    0.819234
4    0.497985
5    0.909348
6    0.000312
7    0.008964
8    0.074377
9    0.134511
dtype: float64

In [ ]:
ser = Series(np.random.rand(3))
print(ser)

def squared(x):
  return x**2

ser.map(squared)

0    0.901265
1    0.590661
2    0.661820
dtype: float64


0    0.812279
1    0.348881
2    0.438006
dtype: float64

In [ ]:
# Series .map method - String operation
Series({1: 'The Green Mile', 2: 'Black Panther', 3: 'The Bourne Identity'}).map(lambda s: len(s.split()))

1    3
2    2
3    3
dtype: int64

In [ ]:
# DataFrame .apply method - down each column (axis=0), across each row (axis=1)
print(df)
print(df.sum(axis=1))
print(df.apply(lambda arr: arr / arr.sum(), axis=1))

          0         1         2         3         4
0  0.207582  0.147820  0.555799  0.841771  0.930090
1  0.440490  0.394001  0.087994  0.085431  0.787785
2  0.558558  0.440427  0.897610  0.184026  0.413851
0    2.683061
1    1.795700
2    2.494470
dtype: float64
          0         1         2         3         4
0  0.077367  0.055094  0.207151  0.313735  0.346652
1  0.245302  0.219413  0.049003  0.047575  0.438706
2  0.223918  0.176561  0.359840  0.073773  0.165907


In [ ]:
# DataFrame .applymap method
print(df)
print(df.sum(axis=1))
df.applymap(lambda x: x / df.sum().sum())

          0         1         2         3         4
0  0.207582  0.147820  0.555799  0.841771  0.930090
1  0.440490  0.394001  0.087994  0.085431  0.787785
2  0.558558  0.440427  0.897610  0.184026  0.413851
0    2.683061
1    1.795700
2    2.494470
dtype: float64


<ipython-input-118-b26a5ea9bff1>:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x / df.sum().sum())


0         1         2         3         4
0  0.029768  0.021198  0.079705  0.120715  0.133380
1  0.063169  0.056502  0.012619  0.012251  0.112973
2  0.080100  0.063160  0.128722  0.026390  0.059348

#Sorting and Ranking

In [ ]:
# Sort series
ser = Series(np.random.rand(5))
print(ser,'\n\n')
ser.sort_values(ascending=True) # Sort DataFrame, default axis=0 (by column)
df = DataFrame(np.random.rand(3,5),columns=['a','b','c','d','e'])
print(df)
df.sort_values(by='d',axis=0)

0    0.249970
1    0.208039
2    0.744192
3    0.627225
4    0.833519
dtype: float64 


          a         b         c         d         e
0  0.704402  0.810833  0.248724  0.711064  0.327600
1  0.202175  0.950123  0.856034  0.857537  0.386686
2  0.083981  0.688228  0.464479  0.425542  0.320528


a         b         c         d         e
2  0.083981  0.688228  0.464479  0.425542  0.320528
0  0.704402  0.810833  0.248724  0.711064  0.327600
1  0.202175  0.950123  0.856034  0.857537  0.386686

In [ ]:
# Sort DataFrame, default axis=0 (by column)
df = DataFrame(np.random.rand(3,5),columns=['a','b','c','d','e'])
print(df)
df.sort_values(by='d',axis=0)

          a         b         c         d         e
0  0.191132  0.216994  0.127462  0.013085  0.386217
1  0.892931  0.375878  0.405669  0.436291  0.840953
2  0.877437  0.698025  0.016860  0.242203  0.774339


a         b         c         d         e
0  0.191132  0.216994  0.127462  0.013085  0.386217
2  0.877437  0.698025  0.016860  0.242203  0.774339
1  0.892931  0.375878  0.405669  0.436291  0.840953

In [ ]:
print(df)

          a         b         c         d         e
0  0.191132  0.216994  0.127462  0.013085  0.386217
1  0.892931  0.375878  0.405669  0.436291  0.840953
2  0.877437  0.698025  0.016860  0.242203  0.774339


In [ ]:
df.loc[[0,1],'c'] = 1
print(df)

          a         b        c         d         e
0  0.191132  0.216994  1.00000  0.013085  0.386217
1  0.892931  0.375878  1.00000  0.436291  0.840953
2  0.877437  0.698025  0.01686  0.242203  0.774339


In [ ]:
df.sort_values(by=['c','a'],axis=0)

a         b        c         d         e
2  0.877437  0.698025  0.01686  0.242203  0.774339
0  0.191132  0.216994  1.00000  0.013085  0.386217
1  0.892931  0.375878  1.00000  0.436291  0.840953

In [ ]:
df.iloc[1:,0]=0.9
print(df)

          a         b        c         d         e
0  0.191132  0.216994  1.00000  0.013085  0.386217
1  0.900000  0.375878  1.00000  0.436291  0.840953
2  0.900000  0.698025  0.01686  0.242203  0.774339


In [ ]:
df.rank(axis=0, method='dense', ascending=False) # method = 'average', 'min', 'max', 'first', 'dense'

a    b    c    d    e
0  2.0  3.0  1.0  3.0  3.0
1  1.0  2.0  1.0  1.0  1.0
2  1.0  1.0  2.0  2.0  2.0

In [ ]:
# Difference of rank methods
df = DataFrame(np.random.rand(5,5),index=['a','b','c','d','e'])
print(df)


          0         1         2         3         4
a  0.855453  0.669530  0.936181  0.681379  0.993619
b  0.247023  0.248547  0.925107  0.491141  0.298866
c  0.537532  0.527920  0.845271  0.894478  0.780397
d  0.369270  0.428709  0.968303  0.087594  0.224714
e  0.606834  0.957944  0.313880  0.973023  0.596475


In [ ]:
df.iloc[1:3,0]=1
df.iloc[3:5,0]=2
print(df)

          0         1         2         3         4
a  0.855453  0.669530  0.936181  0.681379  0.993619
b  1.000000  0.248547  0.925107  0.491141  0.298866
c  1.000000  0.527920  0.845271  0.894478  0.780397
d  2.000000  0.428709  0.968303  0.087594  0.224714
e  2.000000  0.957944  0.313880  0.973023  0.596475


In [ ]:
df.rank(axis=0, method='first', ascending=True)

0    1    2    3    4
a  1.0  4.0  4.0  3.0  5.0
b  2.0  1.0  3.0  2.0  2.0
c  3.0  3.0  2.0  4.0  4.0
d  4.0  2.0  5.0  1.0  1.0
e  5.0  5.0  1.0  5.0  3.0

#Pandas Text Processing

In [ ]:
import re
from numpy import nan as NA
import numpy as np
import pandas as pd
pd.set_option('max_colwidth',150)

#Vectorized String Methods in Pandas

In [ ]:
df = pd.read_html('https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html')
df[1]

Method  \
0             cat()   
1           split()   
2          rsplit()   
3             get()   
4            join()   
5     get_dummies()   
6        contains()   
7         replace()   
8    removeprefix()   
9    removesuffix()   
10         repeat()   
11            pad()   
12         center()   
13          ljust()   
14          rjust()   
15          zfill()   
16           wrap()   
17          slice()   
18  slice_replace()   
19          count()   
20     startswith()   
21       endswith()   
22        findall()   
23          match()   
24        extract()   
25     extractall()   
26            len()   
27          strip()   
28         rstrip()   
29         lstrip()   
30      partition()   
31     rpartition()   
32          lower()   
33       casefold()   
34          upper()   
35           find()   
36          rfind()   
37          index()   
38         rindex()   
39     capitalize()   
40       swapcase()   
41      normalize()   
42      translate()   
43        isalnum()   
44        isalpha()   
45        isdigit()   
46        isspace()   
47        islower()   
48        isupper()   
49        istitle()   
50      isnumeric()   
51      isdecimal()   

                                                                                                                     Description  
0                                                                                                            Concatenate strings  
1                                                                                                     Split strings on delimiter  
2                                                                  Split strings on delimiter working from the end of the string  
3                                                                                Index into each element (retrieve i-th element)  
4                                                               Join strings in each element of the Series with passed separator  
5                                                          Split strings on the delimiter returning DataFrame of dummy variables  
6                                                                     Return boolean array if each string contains pattern/regex  
7      Replace occurrences of pattern/regex/string with some other string or the return value of a callable given the occurrence  
8                                                       Remove prefix from string i.e. only remove if string starts with prefix.  
9                                                         Remove suffix from string i.e. only remove if string ends with suffix.  
10                                                                        Duplicate values (s.str.repeat(3) equivalent to x * 3)  
11                                                                                        Add whitespace to the sides of strings  
12                                                                                                      Equivalent to str.center  
13                                                                                                       Equivalent to str.ljust  
14                                                                                                       Equivalent to str.rjust  
15                                                                                                       Equivalent to str.zfill  
16                                                             Split long strings into lines with length less than a given width  
17                                                                                               Slice each string in the Series  
18                                                                                Replace slice in each string with passed value  
19                                                                                                  Count occurrences of pattern  
20                                        

In [ ]:
print(df[1].index)

RangeIndex(start=0, stop=52, step=1)


In [ ]:
str_df = df[1].set_index('Method')
str_df.head(10)

Description
Method                                                                                                                                   
cat()                                                                                                                 Concatenate strings
split()                                                                                                        Split strings on delimiter
rsplit()                                                                    Split strings on delimiter working from the end of the string
get()                                                                                     Index into each element (retrieve i-th element)
join()                                                                   Join strings in each element of the Series with passed separator
get_dummies()                                                       Split strings on the delimiter returning DataFrame of dummy variables
contains()                                                                     Return boolean array if each string contains pattern/regex
replace()       Replace occurrences of pattern/regex/string with some other string or the return value of a callable given the occurrence
removeprefix()                                                   Remove prefix from string i.e. only remove if string starts with prefix.
removesuffix()                                                     Remove suffix from string i.e. only remove if string ends with suffix.

In [ ]:
print(str_df.index)
str_df.index = str_df.index.str.replace('c','C')
print('=====\n')
print(str_df.index)

Index(['cat()', 'split()', 'rsplit()', 'get()', 'join()', 'get_dummies()',
       'contains()', 'replace()', 'removeprefix()', 'removesuffix()',
       'repeat()', 'pad()', 'center()', 'ljust()', 'rjust()', 'zfill()',
       'wrap()', 'slice()', 'slice_replace()', 'count()', 'startswith()',
       'endswith()', 'findall()', 'match()', 'extract()', 'extractall()',
       'len()', 'strip()', 'rstrip()', 'lstrip()', 'partition()',
       'rpartition()', 'lower()', 'casefold()', 'upper()', 'find()', 'rfind()',
       'index()', 'rindex()', 'capitalize()', 'swapcase()', 'normalize()',
       'translate()', 'isalnum()', 'isalpha()', 'isdigit()', 'isspace()',
       'islower()', 'isupper()', 'istitle()', 'isnumeric()', 'isdecimal()'],
      dtype='object', name='Method')
=====

Index(['Cat()', 'split()', 'rsplit()', 'get()', 'join()', 'get_dummies()',
       'Contains()', 'replaCe()', 'removeprefix()', 'removesuffix()',
       'repeat()', 'pad()', 'Center()', 'ljust()', 'rjust()', 'zfill()',


In [ ]:
names = pd.Series(['anna','melody','jordan','william',NA])
names

0       anna
1     melody
2     jordan
3    william
4        NaN
dtype: object

In [ ]:
# .map approach
#names.map(lambda s: s.capitalize())
names.str.upper()

0       ANNA
1     MELODY
2     JORDAN
3    WILLIAM
4        NaN
dtype: object

In [ ]:
# .map approach with ternary expression
names.map(lambda s: s.capitalize() if pd.notnull(s) else s)

0       Anna
1     Melody
2     Jordan
3    William
4        NaN
dtype: object

In [ ]:
print(names)
print(names.str.get(1))
names.str[1]

0       anna
1     melody
2     jordan
3    william
4        NaN
dtype: object
0      n
1      e
2      o
3      i
4    NaN
dtype: object


0      n
1      e
2      o
3      i
4    NaN
dtype: object

In [ ]:
names.str.slice(0,5)
#names.str[0:5:2]

0     anna
1    melod
2    jorda
3    willi
4      NaN
dtype: object

#Date Range

In [ ]:
# Create date range
dser = pd.Series(pd.date_range(start='1/1/2018', end='1/10/2018').astype(str))
dser

0    2018-01-01
1    2018-01-02
2    2018-01-03
3    2018-01-04
4    2018-01-05
5    2018-01-06
6    2018-01-07
7    2018-01-08
8    2018-01-09
9    2018-01-10
dtype: object

In [ ]:
# str.contains
dser.str.contains('\d{4}')

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

In [ ]:
print(dser)

0    2018-01-01
1    2018-01-02
2    2018-01-03
3    2018-01-04
4    2018-01-05
5    2018-01-06
6    2018-01-07
7    2018-01-08
8    2018-01-09
9    2018-01-10
dtype: object


In [ ]:
# str.extract - Single group
dser.str.extract('-(\d\d)$',expand=True) #if expand is true then output is dataframe, otherwise it will be an object

0
0  01
1  02
2  03
3  04
4  05
5  06
6  07
7  08
8  09
9  10

In [ ]:
pat = '-(?P<month>\d\d)-'
m = re.search(pat, dser[0])
print(dser[0])
print(m.group('month'))
print(m.group(0))
print(m.group(1))

2018-01-01
01
-01-
01


In [ ]:
# str.extract - Multiple groups
#dser.str.extract?

dser.str.extract('((?P<year>\d\d\d\d)-(\d\d))-\d\d', expand=True)

0  year   2
0  2018-01  2018  01
1  2018-01  2018  01
2  2018-01  2018  01
3  2018-01  2018  01
4  2018-01  2018  01
5  2018-01  2018  01
6  2018-01  2018  01
7  2018-01  2018  01
8  2018-01  2018  01
9  2018-01  2018  01

In [ ]:
# str.findall

dser.str.findall('(\d+?)')

0    [2, 0, 1, 8, 0, 1, 0, 1]
1    [2, 0, 1, 8, 0, 1, 0, 2]
2    [2, 0, 1, 8, 0, 1, 0, 3]
3    [2, 0, 1, 8, 0, 1, 0, 4]
4    [2, 0, 1, 8, 0, 1, 0, 5]
5    [2, 0, 1, 8, 0, 1, 0, 6]
6    [2, 0, 1, 8, 0, 1, 0, 7]
7    [2, 0, 1, 8, 0, 1, 0, 8]
8    [2, 0, 1, 8, 0, 1, 0, 9]
9    [2, 0, 1, 8, 0, 1, 1, 0]
dtype: object

In [ ]:
# str.match

dser.str.match('\d\d')

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

In [ ]:
# str.replace

dser.str.replace('-0','-')

0     2018-1-1
1     2018-1-2
2     2018-1-3
3     2018-1-4
4     2018-1-5
5     2018-1-6
6     2018-1-7
7     2018-1-8
8     2018-1-9
9    2018-1-10
dtype: object

In [ ]:
dser.str.split('-|/').str.get(0).str.slice(2,4)

0    18
1    18
2    18
3    18
4    18
5    18
6    18
7    18
8    18
9    18
dtype: object

#Drive

In [ ]:
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
df = pd.read_html('https://www.wmata.com/schedules/timetables/index.cfm', match='Date', header=0)[0]
df.head()

Date                                        Holiday  \
0  Wednesday 1/1/2025                                 New Year's Day   
1    Monday 1/20/2025  Martin Luther King Jr. Day & Inauguration Day   
2    Monday 2/17/2025                                 Presidents Day   
3    Monday 5/26/2025                                   Memorial Day   
4  Thursday 6/19/2025                                     Juneteenth   

         Metrobus Schedule  
0                   Sunday  
1  Saturday + Supplemental  
2  Saturday + Supplemental  
3                   Sunday  
4  Saturday + Supplemental

In [ ]:
# Insert day of the week
#df.drop(columns=['DOW'],inplace=True)
df.insert(0, 'DOW', df['Date'].str.split('\s').str[0])
#df.insert(1, 'DOW', df['Date'].str.extract('(.+?)\d', expand=False))
df.head()

DOW                Date  \
0  Wednesday  Wednesday 1/1/2025   
1     Monday    Monday 1/20/2025   
2     Monday    Monday 2/17/2025   
3     Monday    Monday 5/26/2025   
4   Thursday  Thursday 6/19/2025   

                                         Holiday        Metrobus Schedule  
0                                 New Year's Day                   Sunday  
1  Martin Luther King Jr. Day & Inauguration Day  Saturday + Supplemental  
2                                 Presidents Day  Saturday + Supplemental  
3                                   Memorial Day                   Sunday  
4                                     Juneteenth  Saturday + Supplemental

In [ ]:
df = pd.read_html('https://www.world-airport-codes.com/world-top-30-airports.html', header=0, index_col=0)[0]
df.head(3)

Airport  \
Rank                                                     
1.0   Hartsfield–Jackson Atlanta International Airport   
2.0                        Dubai International Airport   
3.0            Dallas Fort Worth International Airport   

                      Location               Country Code (IATA/ICAO)  \
Rank                                                                    
1.0           Atlanta, Georgia         United States         ATL/KATL   
2.0      Garhoud, Dubai, Dubai  United Arab Emirates         DXB/OMDB   
3.0   Dallas–Fort Worth, Texas         United States         DFW/KDFW   

      Total passengers Rank change % change  
Rank                                         
1.0          104653451         NaN    11.7%  
2.0           86994365           3    31.7%  
3.0           81755538           1    11.4%

In [ ]:
# Extract city/metropolitan area
df.insert(1, 'Metro', df['Location'].str.split(', ').str[0])
df.head(3)

Airport              Metro  \
Rank                                                                        
1.0   Hartsfield–Jackson Atlanta International Airport            Atlanta   
2.0                        Dubai International Airport            Garhoud   
3.0            Dallas Fort Worth International Airport  Dallas–Fort Worth   

                      Location               Country Code (IATA/ICAO)  \
Rank                                                                    
1.0           Atlanta, Georgia         United States         ATL/KATL   
2.0      Garhoud, Dubai, Dubai  United Arab Emirates         DXB/OMDB   
3.0   Dallas–Fort Worth, Texas         United States         DFW/KDFW   

      Total passengers Rank change % change  
Rank                                         
1.0          104653451         NaN    11.7%  
2.0           86994365           3    31.7%  
3.0           81755538           1    11.4%

In [ ]:
# Extract city/metropolitan area
df.insert(2, 'State', df['Location'].str.extract(', (.+)', expand=False))
del df['Location']
df.head(3)

Airport              Metro  \
Rank                                                                        
1.0   Hartsfield–Jackson Atlanta International Airport            Atlanta   
2.0                        Dubai International Airport            Garhoud   
3.0            Dallas Fort Worth International Airport  Dallas–Fort Worth   

             State               Country Code (IATA/ICAO)  Total passengers  \
Rank                                                                          
1.0        Georgia         United States         ATL/KATL         104653451   
2.0   Dubai, Dubai  United Arab Emirates         DXB/OMDB          86994365   
3.0          Texas         United States         DFW/KDFW          81755538   

     Rank change % change  
Rank                       
1.0          NaN    11.7%  
2.0            3    31.7%  
3.0            1    11.4%

In [ ]:
# Split and expand IATA and ICAO airport codes
codes = df['Code (IATA/ICAO)'].str.split('/', expand=True).head()
codes.columns = ['IATA', 'ICAO']
codes.head()

IATA  ICAO
Rank           
1.0   ATL  KATL
2.0   DXB  OMDB
3.0   DFW  KDFW
4.0   LHR  EGLL
5.0   HND  RJTT

In [ ]:
# Insert codes into DataFrame
df.insert(4, 'IATA', codes['IATA'])
df.insert(5, 'ICAO', codes['ICAO'])
del df['Code (IATA/ICAO)']
df.head()

Airport              Metro  \
Rank                                                                        
1.0   Hartsfield–Jackson Atlanta International Airport            Atlanta   
2.0                        Dubai International Airport            Garhoud   
3.0            Dallas Fort Worth International Airport  Dallas–Fort Worth   
4.0                                   Heathrow Airport         Hillingdon   
5.0                               Tokyo Haneda Airport                Ōta   

             State               Country IATA  ICAO  Total passengers  \
Rank                                                                    
1.0        Georgia         United States  ATL  KATL         104653451   
2.0   Dubai, Dubai  United Arab Emirates  DXB  OMDB          86994365   
3.0          Texas         United States  DFW  KDFW          81755538   
4.0         London        United Kingdom  LHR  EGLL          79183364   
5.0          Tokyo                 Japan  HND  RJTT          78719302   

     Rank change % change  
Rank                       
1.0          NaN    11.7%  
2.0            3    31.7%  
3.0            1    11.4%  
4.0            4    28.5%  
5.0           11    55.1%

In [ ]:
# Check dtypes
df.dtypes

Airport             object
Metro               object
State               object
Country             object
IATA                object
ICAO                object
Total passengers     int64
Rank change         object
% change            object
dtype: object

In [ ]:
# Output data to file
df.head(3) # first n records, 5 by default
df.to_csv('top_airports.txt', index=True)